import java.util.Enumeration;
import java.util.HashMap;

import javax.swing.AbstractButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jmulh
 */
public class employee extends javax.swing.JFrame {
    Backend backend = new Backend();
    String empID ="";
    /**
     * Creates new form employee
     */
    public employee(String ID) {
        initComponents();
        HashMap<String,String> empInfo = backend.getEmployeeByID(ID);
        employeeNameText.setText(empInfo.get("Name"));
        employeeIDText.setText(empInfo.get("ID"));
        employeeSSNText.setText(empInfo.get("SSN"));
        locationTxt.setText(empInfo.get("Location"));
        empAddrTxt.setText(empInfo.get("Address"));
        empEmail.setText(empInfo.get("Email"));
        empPhoneNumber.setText(empInfo.get("Phone"));
        empAccessLevelText.setText(empInfo.get("Access"));
        if(empAccessLevelText.getText().equals("Admin")){
            oneBtn.setSelected(false);
            twoBtn.setSelected(true);
            remEmpBtn.setSelected(false);
            empUserFld.setText(empInfo.get("User"));
            empPassFld.setText(empInfo.get("Pass"));
        }
        else{
            oneBtn.setSelected(true);
            twoBtn.setSelected(false);
            remEmpBtn.setSelected(false);
            viewLoginInfo(false);
        }
    }
    public void viewLoginInfo(boolean view){
        empUserFld.setVisible(view);
        empPassFld.setVisible(view);
        userText.setVisible(view);
        passText.setVisible(view);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accessLevelButtons = new javax.swing.ButtonGroup();
        employeeNameText = new javax.swing.JLabel();
        employeeIDText = new javax.swing.JLabel();
        updateEmployeeBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JRadioButton();
        oneBtn = new javax.swing.JRadioButton();
        remEmpBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        empAccessLevelText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        employeeSSNText = new javax.swing.JTextField();
        locationTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        empAddrTxt = new javax.swing.JTextField();
        empWorkingHoursLbl1 = new javax.swing.JLabel();
        empEmail = new javax.swing.JTextField();
        empWorkingHoursLbl2 = new javax.swing.JLabel();
        empPhoneNumber = new javax.swing.JTextField();
        userText = new javax.swing.JLabel();
        empUserFld = new javax.swing.JTextField();
        empPassFld = new javax.swing.JTextField();
        passText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeeNameText.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        employeeNameText.setText("Employee Name");

        employeeIDText.setText("Employee ID");

        updateEmployeeBtn.setText("Update Employee");
        updateEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeBtnActionPerformed(evt);
            }
        });

        accessLevelButtons.add(twoBtn);
        twoBtn.setText("Admin");
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });

        accessLevelButtons.add(oneBtn);
        oneBtn.setText("User");
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });

        accessLevelButtons.add(remEmpBtn);
        remEmpBtn.setText("Remove Employee");
        remEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remEmpBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Current Access Level:");

        empAccessLevelText.setText("accessLevel");

        jLabel2.setText("ID:");

        jLabel4.setText("SSN:");

        jLabel5.setText("Location:");

        employeeSSNText.setText("EmployeeSSN");
        employeeSSNText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSSNTextActionPerformed(evt);
            }
        });

        locationTxt.setText("EmployeeLocation");

        jLabel6.setText("Address:");

        empAddrTxt.setText("EmployeeAddress");

        empWorkingHoursLbl1.setText("Email:");

        empEmail.setText("EmployeeEmail");
        empEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empEmailActionPerformed(evt);
            }
        });

        empWorkingHoursLbl2.setText("Employee Phone Number:");

        empPhoneNumber.setText("EmployeePhoneNumber");

        userText.setText("Username:");

        empUserFld.setText("EmployeeUserName");

        empPassFld.setText("EmployeePassword");

        passText.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(employeeNameText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateEmployeeBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(twoBtn)
                                .addComponent(oneBtn)
                                .addComponent(remEmpBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(employeeSSNText, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(employeeIDText))
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(empAccessLevelText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(empWorkingHoursLbl1)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(empWorkingHoursLbl2)
                                        .addComponent(userText)
                                        .addComponent(passText))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(empAddrTxt)
                                        .addComponent(empPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(empEmail)
                                        .addComponent(empUserFld, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(empPassFld, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                            .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(employeeNameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeIDText)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(employeeSSNText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(empAddrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empWorkingHoursLbl1)
                    .addComponent(empEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empWorkingHoursLbl2)
                    .addComponent(empPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userText)
                    .addComponent(empUserFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passText)
                    .addComponent(empPassFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(empAccessLevelText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(twoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneBtn)
                .addGap(3, 3, 3)
                .addComponent(remEmpBtn)
                .addGap(45, 45, 45)
                .addComponent(updateEmployeeBtn)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeBtnActionPerformed
        int accessLevel;
        if(twoBtn.isSelected()){
            accessLevel = 2;
        }
        else if(oneBtn.isSelected()){
            accessLevel = 1;
        }
        else{
            accessLevel = 0;
        }
        backend.setEmployeeByID(employeeIDText.getText(), employeeSSNText.getText(),locationTxt.getText(), empAddrTxt.getText(), empEmail.getText(), empPhoneNumber.getText(), accessLevel,empUserFld.getText(), empPassFld.getText() );
        this.setVisible(false);
    }//GEN-LAST:event_updateEmployeeBtnActionPerformed

    private void employeeSSNTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSSNTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeSSNTextActionPerformed

    private void empEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empEmailActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        viewLoginInfo(true);
    }//GEN-LAST:event_twoBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        viewLoginInfo(false);
    }//GEN-LAST:event_oneBtnActionPerformed

    private void remEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remEmpBtnActionPerformed
        viewLoginInfo(false);
    }//GEN-LAST:event_remEmpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new employee(0, "", "", "" , new String[0], 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup accessLevelButtons;
    private javax.swing.JLabel empAccessLevelText;
    private javax.swing.JTextField empAddrTxt;
    private javax.swing.JTextField empEmail;
    private javax.swing.JTextField empPassFld;
    private javax.swing.JTextField empPhoneNumber;
    private javax.swing.JTextField empUserFld;
    private javax.swing.JLabel empWorkingHoursLbl1;
    private javax.swing.JLabel empWorkingHoursLbl2;
    private javax.swing.JLabel employeeIDText;
    private javax.swing.JLabel employeeNameText;
    private javax.swing.JTextField employeeSSNText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JRadioButton oneBtn;
    private javax.swing.JLabel passText;
    private javax.swing.JRadioButton remEmpBtn;
    private javax.swing.JRadioButton twoBtn;
    private javax.swing.JButton updateEmployeeBtn;
    private javax.swing.JLabel userText;
    // End of variables declaration//GEN-END:variables
}
