import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jmulh
 */
public class Homepage extends javax.swing.JFrame {
    Backend backend = new Backend();
    int userID;
    String accessLevel;
    CheckInOutSupply checkOutPnl;

    /**
     * 
     * @param userID
     * @param accessLevel 
     */
    public Homepage(int userID, String accessLevel) {
        initComponents();
        setPanelsInvisible();
        this.userID = userID;
        this.accessLevel = accessLevel;
        
        // Only Supervisors can create users
        if(accessLevel.equals("Admin")){
            createUserBtn.setVisible(false);
            viewItemLbl2.setVisible(false);
        }
    }
    
    private void setPanelsInvisible(){
        SuppliesPnl.setVisible(false);
        SuppliersPnl.setVisible(false);
        UsersPnl.setVisible(false);
        MaintenancePnl.setVisible(false);
        sideBarPnl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        MaintenancePnl = new javax.swing.JPanel();
        mtncIDTxt = new javax.swing.JTextField();
        searchBtn4 = new javax.swing.JButton();
        createRepairBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        SuppliersPnl = new javax.swing.JPanel();
        supplierTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        supplierNameLbl = new javax.swing.JLabel();
        supplierPhoneLbl = new javax.swing.JLabel();
        supplierAddressLbl = new javax.swing.JLabel();
        supplierEmailLbl = new javax.swing.JLabel();
        suppliesLbl = new javax.swing.JLabel();
        viewSupplierBtn = new javax.swing.JButton();
        searchBtn2 = new javax.swing.JButton();
        createSupplierBtn = new javax.swing.JButton();
        SuppliesPnl = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        supplyTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        registerSupply = new javax.swing.JButton();
        checkOutBtn = new javax.swing.JButton();
        viewItemBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        UsersPnl = new javax.swing.JPanel();
        empIDText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        viewItemLbl2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchBtn3 = new javax.swing.JButton();
        createUserBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        sideBarPnl = new javax.swing.JPanel();
        viewSuppliesBtn = new javax.swing.JButton();
        viewUserBtn = new javax.swing.JButton();
        ViewSuppliersBtn = new javax.swing.JButton();
        viewRostersBtn = new javax.swing.JButton();
        viewRepairsBtn = new javax.swing.JButton();
        hamburgerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setMaximumSize(new java.awt.Dimension(517, 436));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(514, 436));
        jPanel1.setLayout(new java.awt.CardLayout());

        MaintenancePnl.setMaximumSize(new java.awt.Dimension(517, 436));
        MaintenancePnl.setPreferredSize(new java.awt.Dimension(517, 436));

        searchBtn4.setText("Search");
        searchBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn4ActionPerformed(evt);
            }
        });

        createRepairBtn.setText("Add Record");
        createRepairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRepairBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Serial Number");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Issue", "Location", "Fixed By", "Fix Date", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel12.setText("Maintenance History (Latest 3):");

        javax.swing.GroupLayout MaintenancePnlLayout = new javax.swing.GroupLayout(MaintenancePnl);
        MaintenancePnl.setLayout(MaintenancePnlLayout);
        MaintenancePnlLayout.setHorizontalGroup(
            MaintenancePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaintenancePnlLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(MaintenancePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MaintenancePnlLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(mtncIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn4)
                        .addGap(18, 18, 18)
                        .addComponent(createRepairBtn)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        MaintenancePnlLayout.setVerticalGroup(
            MaintenancePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaintenancePnlLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(MaintenancePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mtncIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn4)
                    .addComponent(createRepairBtn)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(706, Short.MAX_VALUE))
        );

        jPanel1.add(MaintenancePnl, "card2");

        SuppliersPnl.setMaximumSize(new java.awt.Dimension(517, 436));
        SuppliersPnl.setOpaque(false);
        SuppliersPnl.setPreferredSize(new java.awt.Dimension(517, 436));

        jLabel2.setText("Supplier Name:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        supplierNameLbl.setText("NAME");

        supplierPhoneLbl.setText("Phone");

        supplierAddressLbl.setText("Address");

        supplierEmailLbl.setText("Email");

        suppliesLbl.setText("Supplies:");

        viewSupplierBtn.setText("Update");
        viewSupplierBtn.setEnabled(false);
        viewSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupplierBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewSupplierBtn)
                .addGap(76, 76, 76)
                .addComponent(supplierNameLbl)
                .addGap(18, 18, 18)
                .addComponent(supplierPhoneLbl)
                .addGap(18, 18, 18)
                .addComponent(supplierAddressLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supplierEmailLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suppliesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierNameLbl)
                    .addComponent(supplierPhoneLbl)
                    .addComponent(supplierAddressLbl)
                    .addComponent(supplierEmailLbl)
                    .addComponent(suppliesLbl)
                    .addComponent(viewSupplierBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchBtn2.setText("Search");
        searchBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn2ActionPerformed(evt);
            }
        });

        createSupplierBtn.setText("Create Supplier");
        createSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSupplierBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SuppliersPnlLayout = new javax.swing.GroupLayout(SuppliersPnl);
        SuppliersPnl.setLayout(SuppliersPnlLayout);
        SuppliersPnlLayout.setHorizontalGroup(
            SuppliersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuppliersPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(SuppliersPnlLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supplierTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createSupplierBtn)
                .addGap(60, 60, 60))
        );
        SuppliersPnlLayout.setVerticalGroup(
            SuppliersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuppliersPnlLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(SuppliersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(supplierTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn2)
                    .addComponent(createSupplierBtn))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(SuppliersPnl, "card3");

        SuppliesPnl.setMaximumSize(new java.awt.Dimension(517, 436));
        SuppliesPnl.setPreferredSize(new java.awt.Dimension(517, 436));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Serial Number");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        registerSupply.setText("Add Device");
        registerSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerSupplyActionPerformed(evt);
            }
        });

        checkOutBtn.setText("Check Out/ In");
        checkOutBtn.setEnabled(false);
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });

        viewItemBtn.setText("View");
        viewItemBtn.setEnabled(false);
        viewItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemBtnActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Model", "Status", "Access", "Condition"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout SuppliesPnlLayout = new javax.swing.GroupLayout(SuppliesPnl);
        SuppliesPnl.setLayout(SuppliesPnlLayout);
        SuppliesPnlLayout.setHorizontalGroup(
            SuppliesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuppliesPnlLayout.createSequentialGroup()
                .addGroup(SuppliesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SuppliesPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SuppliesPnlLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(SuppliesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SuppliesPnlLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(supplyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(searchBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerSupply)))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuppliesPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SuppliesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuppliesPnlLayout.createSequentialGroup()
                        .addComponent(viewItemBtn)
                        .addGap(252, 252, 252))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuppliesPnlLayout.createSequentialGroup()
                        .addComponent(checkOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))))
        );
        SuppliesPnlLayout.setVerticalGroup(
            SuppliesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuppliesPnlLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(SuppliesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(supplyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(registerSupply))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(checkOutBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewItemBtn)
                .addGap(703, 703, 703)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(SuppliesPnl, "card4");

        UsersPnl.setMaximumSize(new java.awt.Dimension(517, 436));
        UsersPnl.setPreferredSize(new java.awt.Dimension(517, 436));

        jLabel3.setText("Employee ID/Name:");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        viewItemLbl2.setText("Deactivate");
        viewItemLbl2.setEnabled(false);
        viewItemLbl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemLbl2ActionPerformed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Status", "Name", "SSN", "Address", "Phone", "Email", "Access"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewItemLbl2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewItemLbl2)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        searchBtn3.setText("Search");
        searchBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn3ActionPerformed(evt);
            }
        });

        createUserBtn.setText("Register Employee");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsersPnlLayout = new javax.swing.GroupLayout(UsersPnl);
        UsersPnl.setLayout(UsersPnlLayout);
        UsersPnlLayout.setHorizontalGroup(
            UsersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersPnlLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(empIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn3)
                .addGap(56, 56, 56)
                .addComponent(createUserBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UsersPnlLayout.setVerticalGroup(
            UsersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersPnlLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(UsersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(searchBtn3)
                    .addComponent(createUserBtn))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(UsersPnl, "card2");

        jPanel4.setLayout(new java.awt.CardLayout());

        sideBarPnl.setBackground(new java.awt.Color(153, 0, 255));

        viewSuppliesBtn.setText("View Devices");
        viewSuppliesBtn.setPreferredSize(new java.awt.Dimension(125, 23));
        viewSuppliesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSuppliesBtnActionPerformed(evt);
            }
        });
        sideBarPnl.add(viewSuppliesBtn);

        viewUserBtn.setText("View Users");
        viewUserBtn.setPreferredSize(new java.awt.Dimension(125, 23));
        viewUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserBtnActionPerformed(evt);
            }
        });
        sideBarPnl.add(viewUserBtn);

        ViewSuppliersBtn.setText("View Suppliers");
        ViewSuppliersBtn.setPreferredSize(new java.awt.Dimension(125, 23));
        ViewSuppliersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSuppliersBtnActionPerformed(evt);
            }
        });
        sideBarPnl.add(ViewSuppliersBtn);

        viewRostersBtn.setText("View Rosters");
        viewRostersBtn.setEnabled(false);
        viewRostersBtn.setPreferredSize(new java.awt.Dimension(125, 23));
        viewRostersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRostersBtnActionPerformed(evt);
            }
        });
        sideBarPnl.add(viewRostersBtn);

        viewRepairsBtn.setText("Maintenance");
        viewRepairsBtn.setMaximumSize(new java.awt.Dimension(127, 180));
        viewRepairsBtn.setPreferredSize(new java.awt.Dimension(125, 23));
        viewRepairsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRepairsBtnActionPerformed(evt);
            }
        });
        sideBarPnl.add(viewRepairsBtn);

        hamburgerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8-menu-30.png"))); // NOI18N
        hamburgerBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        hamburgerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburgerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hamburgerBtn)
                            .addComponent(sideBarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hamburgerBtn)
                        .addGap(18, 18, 18)
                        .addComponent(sideBarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewSuppliesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSuppliesBtnActionPerformed
        setPanelsInvisible();
        SuppliesPnl.setVisible(true);
    }//GEN-LAST:event_viewSuppliesBtnActionPerformed

    private void viewUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUserBtnActionPerformed
        setPanelsInvisible();
        UsersPnl.setVisible(true);
    }//GEN-LAST:event_viewUserBtnActionPerformed

    private void itemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemTextActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        this.checkOutPnl.setVisible(true);
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

        String dataRequested = "";
        if(SuppliesPnl.isVisible()){
            dataRequested = "supplies";
        }
        else if (UsersPnl.isVisible()){
            dataRequested = "users";
        }
        else if (SuppliersPnl.isVisible()){
            dataRequested = "suppliers";
        }
        else if (MaintenancePnl.isVisible()){
            dataRequested = "maintenance";
        }
        else{
            System.out.println("Error: No panel is visible");
        }
        
        String ID;
        switch(dataRequested) {
            case "supplies":
                ID = supplyTxt.getText();
                break;
            case "suppliers":
                ID = supplierTxt.getText();
                break;
            case "users":
                ID = empIDText.getText();
                break;
            default:
                ID = mtncIDTxt.getText();
                break;
        }
        
        HashMap<String,String> result = backend.fetchPnlObjectItems(ID, dataRequested);
        if(result != null){
            if(dataRequested.equals("supplies")){
                
                DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
                model.setValueAt(result.get("Type"), 0, 0);
                model.setValueAt(result.get("Model"), 0, 1);
                model.setValueAt(result.get("Status"), 0, 2);
                model.setValueAt(result.get("Access"), 0, 3);
                model.setValueAt(result.get("Condition"), 0, 4);
                
                if (result.get("Status").equals("UNASSIGNED")) {
                    checkOutBtn.setText("Check Out");
                } else {
                    checkOutBtn.setText("Check In");
                }
                
                // Initialize checkOutPnl
                if (checkOutPnl == null) {
                    checkOutPnl = new CheckInOutSupply();
                }
                
                checkOutPnl.initialize(this.userID, result.get("Type"), ID, result.get("Status").equals("UNASSIGNED"));
                viewItemBtn.setEnabled(true);
                checkOutBtn.setEnabled(true);
            }
            if(dataRequested.equals("suppliers")){
                supplierNameLbl.setText(result.get("Name"));
                supplierAddressLbl.setText(result.get("Address"));
                supplierPhoneLbl.setText(result.get("Phone"));
                supplierEmailLbl.setText(result.get("Email"));
                suppliesLbl.setText(result.get("itemsSupplied"));
                viewSupplierBtn.setEnabled(true);
            }
            if(dataRequested.equals("users")){
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                if (result.get("is_active").equals("1")) {
                    model.setValueAt("Active", 0, 0);
                    viewItemLbl2.setText("Deactivate");
                } else {
                    model.setValueAt("Inactive", 0, 0);
                    viewItemLbl2.setText("Activate");
                }
                viewItemLbl2.setEnabled(true);
                model.setValueAt(result.get("name"), 0, 1);
                model.setValueAt(result.get("ssn"), 0, 2);
                model.setValueAt(result.get("address"), 0, 3);
                model.setValueAt(result.get("email"), 0, 5);
                model.setValueAt(result.get("phone"), 0, 4);
                model.setValueAt(result.get("access"), 0, 6);
            }
            if(dataRequested.equals("maintenance")){
                
                
                DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
                for (int i =1; i < 4; i++) {
                    if (result.containsKey("mRecord"+i+".issue")) {
                        model.setValueAt(result.get("mRecord"+i+".issue"), i-1, 0);
                    }
                    if (result.containsKey("mRecord"+i+".location")) {
                        model.setValueAt(result.get("mRecord"+i+".location"), i-1, 1);
                    }
                    if (result.containsKey("mRecord"+i+".by")) {
                        model.setValueAt(result.get("mRecord"+i+".by"), i-1, 2);
                    }
                    if (result.containsKey("mRecord"+i+".at")) {
                        model.setValueAt(result.get("mRecord"+i+".at"), i-1, 3);
                    }
                    if (result.containsKey("mRecord"+i+".cost")) {
                        model.setValueAt(result.get("mRecord"+i+".cost"), i-1, 4);
                    }
                }
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void itemText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemText1ActionPerformed

    private void searchBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn2ActionPerformed
        searchBtnActionPerformed(evt);
    }//GEN-LAST:event_searchBtn2ActionPerformed

    private void itemText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemText2ActionPerformed

    private void searchBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn3ActionPerformed
        searchBtnActionPerformed(evt);
    }//GEN-LAST:event_searchBtn3ActionPerformed

    private void hamburgerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburgerBtnActionPerformed
        sideBarPnl.setVisible(true);
    }//GEN-LAST:event_hamburgerBtnActionPerformed

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        newUser newUser = new newUser();
        newUser.setVisible(true);
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void ViewSuppliersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSuppliersBtnActionPerformed
        setPanelsInvisible();
        SuppliersPnl.setVisible(true);
    }//GEN-LAST:event_ViewSuppliersBtnActionPerformed

    private void viewRostersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRostersBtnActionPerformed
        setPanelsInvisible();
        supplyRoster supplyRoster = new supplyRoster();
        supplyRoster.setVisible(true);
    }//GEN-LAST:event_viewRostersBtnActionPerformed

    private void viewRepairsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRepairsBtnActionPerformed
        setPanelsInvisible();
        MaintenancePnl.setVisible(true);
    }//GEN-LAST:event_viewRepairsBtnActionPerformed

    private void createRepairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRepairBtnActionPerformed
        maintenance mPnl = new maintenance("","","","","","");
        mPnl.setVisible(true);
    }//GEN-LAST:event_createRepairBtnActionPerformed

    private void searchBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn4ActionPerformed
        searchBtnActionPerformed(evt);
    }//GEN-LAST:event_searchBtn4ActionPerformed

    private void empIDText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIDText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIDText1ActionPerformed

    private void viewItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemBtnActionPerformed
        supply supply = new supply(supplyTxt.getText());
        supply.setVisible(true);
    }//GEN-LAST:event_viewItemBtnActionPerformed

    private void registerSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerSupplyActionPerformed
        newSupply newSupply = new newSupply();
        newSupply.setVisible(true);
    }//GEN-LAST:event_registerSupplyActionPerformed

    private void viewSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupplierBtnActionPerformed
        newSupplier newSupplier = new newSupplier(supplierNameLbl.getText(), supplierPhoneLbl.getText(), supplierAddressLbl.getText(), supplierEmailLbl.getText());
        newSupplier.setVisible(true);
    }//GEN-LAST:event_viewSupplierBtnActionPerformed

    private void createSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSupplierBtnActionPerformed
        newSupplier newSupplier = new newSupplier();
        newSupplier.setVisible(true);
    }//GEN-LAST:event_createSupplierBtnActionPerformed

    private void viewItemLbl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemLbl2ActionPerformed
        String empID = empIDText.getText();
        
        if (viewItemLbl2.getText().equals("Deactivate") 
                && jTable1.getModel().getValueAt(0, 6).equals("Employee") 
                && backend.userHasDevice(empID)) {
            JOptionPane.showMessageDialog(new javax.swing.JFrame(), 
                                          "A Device is assigned to this Employee",
                                          "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean activate = viewItemLbl2.getText().equals("Activate");
            backend.updateUserStatus(empID, activate);
            JOptionPane.showMessageDialog(new javax.swing.JFrame(), 
                                          "User is " + (activate ? "activated!" : "deactivated!"),
                                          "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_viewItemLbl2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MaintenancePnl;
    private javax.swing.JPanel SuppliersPnl;
    private javax.swing.JPanel SuppliesPnl;
    private javax.swing.JPanel UsersPnl;
    private javax.swing.JButton ViewSuppliersBtn;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JButton createRepairBtn;
    private javax.swing.JButton createSupplierBtn;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JTextField empIDText;
    private javax.swing.JButton hamburgerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField mtncIDTxt;
    private javax.swing.JButton registerSupply;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtn2;
    private javax.swing.JButton searchBtn3;
    private javax.swing.JButton searchBtn4;
    private javax.swing.JPanel sideBarPnl;
    private javax.swing.JLabel supplierAddressLbl;
    private javax.swing.JLabel supplierEmailLbl;
    private javax.swing.JLabel supplierNameLbl;
    private javax.swing.JLabel supplierPhoneLbl;
    private javax.swing.JTextField supplierTxt;
    private javax.swing.JLabel suppliesLbl;
    private javax.swing.JTextField supplyTxt;
    private javax.swing.JButton viewItemBtn;
    private javax.swing.JButton viewItemLbl2;
    private javax.swing.JButton viewRepairsBtn;
    private javax.swing.JButton viewRostersBtn;
    private javax.swing.JButton viewSupplierBtn;
    private javax.swing.JButton viewSuppliesBtn;
    private javax.swing.JButton viewUserBtn;
    // End of variables declaration//GEN-END:variables
}
